default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graduateexam_development  
test:
  <<: *default
  database: graduateexam_test

production:
  <<: *default
  database: graduateexam_production
  username: graduateexam
  password: <%= ENV['GRADUATEEXAM_DATABASE_PASSWORD'] %>
